# Generated by Django 3.0 on 2020-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=45, unique=True)),
                ('birth_date', models.DateField(db_column='Birth_Date')),
                ('death_date', models.DateField(blank=True, db_column='Death_Date', null=True)),
            ],
            options={
                'db_table': 'compouser',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Compousers',
        ),
    ]
